### ISSUE TITLE
是否可以适配monsterbaration插件中的一个选项？

### ISSUE THREAD

**Issue by minecraftyusei** [1235789gzy1/HVSinicization#9]
这个插件有一个功能是战斗结束后会提供一个本局对战中使用的技能、消耗品的统计（show attack/skill/spell/item usage at end of battle），希望未来的更新中可以加入

**Comment by minecraftyusei** [comment]
不好意思插件名字打错了，monsterbation

**Comment by 1235789gzy1** [comment]
> 这个插件有一个功能是战斗结束后会提供一个本局对战中使用的技能、消耗品的统计（show attack/skill/spell/item usage at end of battle），希望未来的更新中可以加入

~~是日志汉化顶替了这个插件的统计信息嘛？~~
好吧，我试了下没试出来，结果逃跑的时候看到了消耗统计

**Comment by minecraftyusei** [comment]
感谢作者大大的回复！
我猜测是的，这是关闭汉化后的战斗结算图（变色和上面的伤害类型统计表都是monsterbation插件的功能）


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "1235789gzy1/HVSinicization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 晚上10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1235789gzy1/HVSinicization] 是否可以适配monsterbaration插件中的一个选项？ (Issue #9)





  
这个插件有一个功能是战斗结束后会提供一个本局对战中使用的技能、消耗品的统计（show attack/skill/spell/item usage at end of battle），希望未来的更新中可以加入
  
是日志汉化顶替了这个插件的统计信息嘛？

**Comment by 1235789gzy1** [comment]
看起来直接添加对应的汉化没法汉化最后的统计部分，等待真正的大佬研究下吧，咕咕咕。
~~另外我其实是算搬运工来着~~

**Comment by minecraftyusei** [comment]
function ShowUsage() {
&nbsp; &nbsp; if ( !cfg.trackUsage || JSON.stringify(combatlog.used) == '{}' ) return;
&nbsp; &nbsp; var td = log.insertBefore(document.createElement('tbody'), log.firstChild).appendChild(document.createElement('tr')).appendChild(document.createElement('td'));
&nbsp; &nbsp; td.className = 'tlb';
&nbsp; &nbsp; td.innerHTML = 'Used: ' + JSON.stringify(combatlog.used).replace('{','').replace('}','').replace(/"/g,'').replace(/:/g,': ').replace(/,/g,', '); }



这是它关于统计的函数。有可能把它和与之相关的内容集成到汉化插件里吗？（只学过c++的编程小白，这个语言是什么？）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1235789gzy1/HVSinicization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1235789gzy1/HVSinicization] 是否可以适配monsterbaration插件中的一个选项？ (Issue #9)





 
看起来直接添加对应的汉化没法汉化最后的统计部分，等待真正的大佬研究下吧，咕咕咕。
 另外我其实是算搬运工来着

**Comment by 1235789gzy1** [comment]
看起来最好的解决方法还是直接去汉化monsterbation插件最好
